version: "3.9"

services:
  api:
    container_name: genomiq_api
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run dev:api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  worker:
    container_name: genomiq_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run dev:worker
    env_file:
      - .env.docker
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: genomiq_mongo
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    container_name: genomiq_redis
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo_data:
